const REFRESH_TOKEN_HEADER = 'refresh-token';
const ACCESS_TOKEN_VALIDITY_SECONDS = 3600;
const REFRESH_TOKEN_VALIDITY_SECONDS = 2592000;

module.exports = {
    REFRESH_TOKEN_HEADER,
    ACCESS_TOKEN_VALIDITY_SECONDS,
    REFRESH_TOKEN_VALIDITY_SECONDS
};